### ISSUE TITLE
Add Social Section

### ISSUE THREAD

**Issue by Abhinab04** [divyanshudhruv/Minifolio#161]
wanted to add social media section at footer for enhancement of website

**Comment by divyanshudhruv** [comment]
@Abhinab04 please refer to #116

**Comment by divyanshudhruv** [comment]
If you are able to create such type of buttons in navbar below the text in one horizontal line instead of creating the buttons to the right side of the footer text, I can assign it to you too.

You can share the screenshot of both cases-
- buttons on right of the footer text
- buttons below the footer text

### Image
![image](https://github.com/user-attachments/assets/b645ce4b-68f2-442d-811d-68b0a1c46594)

**Comment by Abhinab04** [comment]
sure, i can create that ,its more like contact us page

**Comment by divyanshudhruv** [comment]
@Abhinab04 I mean, can you create those 3-4 buttons just like the buttons shown in the screen shot inside the footer?

Okay, I am assigning you and please share the screen shot before opening the pull request. Good luck 👍

**Comment by Abhinab04** [comment]
light theme:
![Screenshot 2024-10-10 214538](https://github.com/user-attachments/assets/cc686bc4-21fc-48ba-8760-d6776de84ac6)
dark theme:
![Screenshot 2024-10-10 214553](https://github.com/user-attachments/assets/4f980648-12f7-4438-94b7-f6d3b9af6329)
is it looking good @divyanshudhruv

**Comment by divyanshudhruv** [comment]
@Abhinab04 can you re-fork the repository with `dev-main` as the branch because we will be merging it to that branch. You can pull the `dev-main` branch and then add the required files for the social section. And don't worry if the navbar is not as same as your navbar, because the navbar is merged in a different branch. 👍

**Review: The icons are looking too big, try to make them small and add spacing or margin above the icons so that the text and icons do not overlap. It will look clean then. Also, if possible, you can add a square box with some border-radius and border and then the icon inside it just like this -**

### Image
> <img src="https://github.com/user-attachments/assets/833f8a97-9e00-42e9-8230-114422855371" width="50px">

**Comment by divyanshudhruv** [comment]
Yeah, that looks fine. 
@Abhinab04 You can open the pull request, I'll merge it in 2-3 days.

**Comment by Abhinab04** [comment]
https://github.com/divyanshudhruv/Minifolio/pull/172 @divyanshudhruv ,i opened the pr kindly review it,thankyou
